# let's analyze the csv files

In [131]:
import pandas as pd
df_1 = pd.read_csv(r"C:\Users\peter\OneDrive\Desktop\final_exam\interviews\incidenti_stradali_ultimi_5_anni.csv")
df_1.shape

(90144, 16)

In [132]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 90144 entries, 0 to 90143
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATAFLOW          90144 non-null  str
 1   FREQ              90144 non-null  str
 2   REF_AREA          90144 non-null  int64
 3   DATA_TYPE         90144 non-null  str
 4   RESULT            90144 non-null  str
 5   TIME_PERIOD       90144 non-null  int64
 6   OBS_VALUE         90144 non-null  int64
 7   OBS_STATUS        0 non-null      float64
 8   NOTE_DS           0 non-null      float64
 9   NOTE_REF_AREA     0 non-null      float64
 10  NOTE_DATA_TYPE    0 non-null      float64
 11  NOTE_RESULT       0 non-null      float64
 12  NOTE_TIME_PERIOD  0 non-null      float64
 13  BASE_PER          0 non-null      float64
 14  UNIT_MEAS         0 non-null      float64
 15  UNIT_MULT         0 non-null      float64
dtypes: float64(9), int64(3), str(4)
memory usage: 11.0 MB

In [133]:
df_1.sample(10)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
87833,IT1:41_983(1.0),A,108013,ROADACC,9,2021,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84857,IT1:41_983(1.0),A,97084,ROADACC,9,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9364,IT1:41_983(1.0),A,6005,KILLINJ,F,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36473,IT1:41_983(1.0),A,26011,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7305,IT1:41_983(1.0),A,4179,KILLINJ,F,2021,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53945,IT1:41_983(1.0),A,58066,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57564,IT1:41_983(1.0),A,62034,KILLINJ,F,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23816,IT1:41_983(1.0),A,17042,ROADACC,9,2021,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7309,IT1:41_983(1.0),A,4179,KILLINJ,M,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16908,IT1:41_983(1.0),A,13075,KILLINJ,F,2024,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# after reviewing df_1, i begin cleaning it.

In [134]:
df_1.columns

Index(['DATAFLOW', 'FREQ', 'REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD',
       'OBS_VALUE', 'OBS_STATUS', 'NOTE_DS', 'NOTE_REF_AREA', 'NOTE_DATA_TYPE',
       'NOTE_RESULT', 'NOTE_TIME_PERIOD', 'BASE_PER', 'UNIT_MEAS',
       'UNIT_MULT'],
      dtype='str')

In [135]:
cars_accidents = df_1.copy()
cols_1 = ['DATAFLOW',
          'FREQ',
          'OBS_STATUS',
          'NOTE_DS',
          'NOTE_REF_AREA',
          'NOTE_DATA_TYPE',
          'NOTE_RESULT',
          'NOTE_TIME_PERIOD',
          'BASE_PER',
          'UNIT_MEAS',
          'UNIT_MULT']
cars_accidents.drop(columns=cols_1, inplace=True)
cars_accidents.shape

(90144, 5)

In [136]:
cars_accidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 90144 entries, 0 to 90143
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   REF_AREA     90144 non-null  int64
 1   DATA_TYPE    90144 non-null  str
 2   RESULT       90144 non-null  str
 3   TIME_PERIOD  90144 non-null  int64
 4   OBS_VALUE    90144 non-null  int64
dtypes: int64(3), str(2)
memory usage: 3.4 MB

In [137]:
cars_accidents.sample(10)

       REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
59329     64016   KILLINJ      F         2022          0
16369     12143   KILLINJ      M         2024          0
79505     90047   KILLINJ      M         2022          3
88708    109032   ROADACC      9         2023          6
69533     76008   KILLINJ      F         2023          3
6382       4092   KILLINJ      F         2022          2
49158     50016   KILLINJ      M         2023          1
21056     16049   KILLINJ      M         2022          0
60268     64101   KILLINJ      M         2024          0
47413     44064   KILLINJ      F         2022          4

In [138]:
cars_accidents = cars_accidents.rename(columns={'REF_AREA': 'id_code','DATA_TYPE':'type','RESULT':'outcome','TIME_PERIOD':'year','OBS_VALUE':'obs_value'})
cars_accidents.head(10)

   id_code     type outcome  year  obs_value
0     1001  KILLINJ       F  2021          2
1     1001  KILLINJ       F  2022          5
2     1001  KILLINJ       F  2023          6
3     1001  KILLINJ       F  2024          5
4     1001  KILLINJ       M  2021          0
5     1001  KILLINJ       M  2022          0
6     1001  KILLINJ       M  2023          1
7     1001  KILLINJ       M  2024          0
8     1001  ROADACC       9  2021          2
9     1001  ROADACC       9  2022          3

In [139]:
cars_accidents['outcome'] = cars_accidents['outcome'].replace('9','')
cars_accidents['metric'] = cars_accidents['type'] + cars_accidents['outcome']
cars_accidents.head(10)

   id_code     type outcome  year  obs_value    metric
0     1001  KILLINJ       F  2021          2  KILLINJF
1     1001  KILLINJ       F  2022          5  KILLINJF
2     1001  KILLINJ       F  2023          6  KILLINJF
3     1001  KILLINJ       F  2024          5  KILLINJF
4     1001  KILLINJ       M  2021          0  KILLINJM
5     1001  KILLINJ       M  2022          0  KILLINJM
6     1001  KILLINJ       M  2023          1  KILLINJM
7     1001  KILLINJ       M  2024          0  KILLINJM
8     1001  ROADACC          2021          2   ROADACC
9     1001  ROADACC          2022          3   ROADACC

In [140]:
cars_accidents = cars_accidents.drop(columns=['type','outcome'])
cars_accidents['metric'] = cars_accidents['metric'].replace({'KILLINJF':'injured', 'KILLINJM' : 'deaths', 'ROADACC' : 'road_acc'})
cars_accidents = cars_accidents[['id_code','year','metric','obs_value']]
cars_accidents.head(10)

   id_code  year    metric  obs_value
0     1001  2021   injured          2
1     1001  2022   injured          5
2     1001  2023   injured          6
3     1001  2024   injured          5
4     1001  2021    deaths          0
5     1001  2022    deaths          0
6     1001  2023    deaths          1
7     1001  2024    deaths          0
8     1001  2021  road_acc          2
9     1001  2022  road_acc          3

In [150]:
cars_accidents_2021_2025 = cars_accidents.pivot_table(index=['id_code','year'],columns=['metric'], values='obs_value').reset_index()
cars_accidents_2021_2025.columns.name = None
c = ['deaths', 'injured', 'road_acc']
cars_accidents_2021_2025[c] = cars_accidents_2021_2025[c].astype('int64')
cars_accidents_2021_2025.sample(10)

       id_code  year  deaths  injured  road_acc
1073      1292  2023       1       77        59
16193    48031  2023       0        2         2
7891     17030  2023       0        0         0
9731     20013  2022       0        3         2
13564    30081  2021       0        0         0
16520    51012  2022       1       42        33
13565    30081  2022       0        0         0
21021    66071  2022       0        4         4
27977    96086  2024       3        0         2
21401    68016  2023       0        0         0